server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: accountModule
        uri: http://localhost:8087/
        predicates:
        - Path=/accounts/**
      - id: loanModule
        uri: http://localhost:8088/
        predicates:
        - Path=/loans/**